### ISSUE TITLE
Page on site with /blog slug overwrites post page

### ISSUE THREAD

**Issue by scottopolis** [staticfuse/gatsby-theme-publisher#17]
I have a site with a /blog page that uses a page template to display posts. If I also have /blog as my blogURI, the result is that I have no blog archive page at all. It's a bit of an edge case, but the blogURI should overwrite any other page at that slug.

**Comment by justinwhall** [comment]
Are you saying you have a `/src/pages/blog.js` file? Gatsby places this at the top of the hierarchy order and I think we should too. Or are you talking about create a /blog page with the createPage API with a template from, say, `/src/templates/`. If that latter is the case, I agree. `blogURI` should override. I think we should also log a warning to the console when gatsby boots if there is any sort of conflict/overriding.

**Comment by scottopolis** [comment]
No I have a page with the slug “/blog” in my WordPress menu, and blogURI is set to “/blog”. The result is a blank page at /blog. You can try it yourself. 

Thanks,

Scott Bolinger

**Comment by justinwhall** [comment]
This makes total sense. Just pushed a fix.
