### ISSUE TITLE
Handle duplicate menu slugs

### ISSUE THREAD

**Issue by scottopolis** [staticfuse/gatsby-theme-publisher#25]
If we pull in a WP menu and we use our starter pages, there will be duplicate slugs like /about and /contact. Right now Gatsby throws an error and the WP page gets priority.

If we use a WP menu and the starter pages, how do we make menu links? We'd have to combine them and in the case described above, we'd have 2 about pages.

The easiest thing here is just to tell people to not use both WP menu and starter pages.

**Comment by justinwhall** [comment]
https://github.com/staticfuse/gatsby-theme-publisher/commit/1cc45dbff10b6cc1b676f63ee1d69d838d2d7cc7#diff-4d9e726975426dc1d53f1eecec7af230R246

Create `/context-2/` and ideally check if _that exists_. If it does, increment again until there is an available slug.

**Comment by scottopolis** [comment]
Whatever path is created also needs to be passed to the menu here: https://github.com/staticfuse/gatsby-theme-publisher/blob/8b351eae7ffde4ab65abfa38c4e2ad1b3da90b66/gatsby-theme-publisher/src/components/Menu.js#L301-L302
