### ISSUE TITLE
Component export paths

### ISSUE THREAD

**Issue by scottopolis** [staticfuse/gatsby-theme-publisher#29]
When I shadow a component, such as templates/about/index.js, I get a build error about the dependency paths like this one:

`import SEO from '../../components/SEO'`

For this to work, the path needs to be changed to something like:

`import SEO from '../../../../../node_modules/@staticfuse/gatsby-theme-publisher/src/components/SEO.js'`

That seems like a bit much.

Can we export our components separately so we can do this:

`import { SEO } from '@staticfuse/gatsby-theme-publisher'`

That would be much easier.

**Comment by justinwhall** [comment]
I believe this is what you are looking for:

`import SEO from '@staticfuse/gatsby-theme-publisher/src/components/SEO'`

**Comment by justinwhall** [comment]
Resolved here: https://github.com/staticfuse/staticfuse.com/commit/74d871e9cfb238097cce1deab95ba691e633bf66
